name: Push

on:
  push:
    branches: [main, maintenance/*]
  pull_request:
    branches: [main, maintenance/*]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.python-version }}" = "3.12" ]; then
            pip install setuptools
          fi
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pip install -e .
      - name: Run tests with coverage
        run: |
          pytest --cov=constellaxion --cov-report=html --cov-report=xml tests/
